apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: rootpass
  mysql-password: wordpresspass
  mysql-user: wordpress
  mysql-database: wordpress
