apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-webapp.fullname" . }}
  labels:
    {{- include "example-webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "example-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "example-webapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: {{ include "example-webapp.fullname" . }}-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "example-webapp.fullname" . }}-redis
                  key: redis-password
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
