apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Environment variables
  APP_ENV: "production"
  API_URL: "http://api.example.com"
  LOG_LEVEL: "info"
  
  # Configuration file
  config.json: |
    {
      "database": {
        "host": "db.example.com",
        "port": "5432",
        "name": "myapp"
      },
      "cache": {
        "enabled": true,
        "ttl": 3600
      }
    }
  
  # Properties file
  app.properties: |
    app.name=MyApp
    app.description=Example application
    app.version=1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: app
    image: nginx
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_ENV
    volumeMounts:
    - name: config
      mountPath: /etc/config
  volumes:
  - name: config
    configMap:
      name: app-config
