apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: three-tier-app
type: Opaque
stringData:
  mongodb_uri: "mongodb://user:password@mongodb:27017/admin"
  mongodb_user: "admin"
  mongodb_password: "secure-password"
