apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.wordpress.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.wordpress.image.name }}:{{ .Values.wordpress.image.tag  }}"
          env:
            # - name: WP_SITEURL
            #   value: ${WP_HOME}/akagalkar
            - name: WORDPRESS_DB_HOST
              value:  {{ .Values.wordpress.env.host }}
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-app.fullname" . | printf "%s-%s"  "secret-wordpress" }}
                  key: mysql-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-app.fullname" . | printf "%s-%s"  "secret-wordpress" }}
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-app.fullname" . | printf "%s-%s"  "secret-wordpress" }}
                  key: mysql-database
          ports:
            - containerPort: {{  .Values.wordpress.service.containerPort }}
              name: wordpress
          volumeMounts:
            - name:  {{ include "my-app.fullname" . | printf "%s-%s"  "persistent-storage" }}
              mountPath: /var/www/html
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
      - name:  {{ include "my-app.fullname" . | printf "%s-%s"  "persistent-storage" }}
        persistentVolumeClaim:
          claimName:  {{ include "my-app.fullname" . | printf "%s-%s"  "pvc-wordpress" }}
