apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . | printf "%s-%s"  "svc-wordpress" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - port: {{ .Values.wordpress.service.port }}
  selector:
    app: {{ include "my-app.name" . }}