apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . | printf "%s-%s"  "secret-wordpress" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-root-password: rootpass
  mysql-password: wordpresspass
  mysql-user: wordpress
  mysql-database: wordpress
