apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-viewer
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-manager
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  serviceAccountName: app-viewer
  containers:
  - name: nginx
    image: nginx:1.20
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
